### ISSUE TITLE
Add contributor guidelines to readme

### ISSUE THREAD

**Issue by laura-ham** [semi-technologies/weaviate-io#104]
For example how to open issues (make a template?), how to write commit messages (start with gh-xx to refer to issue the commit is tackling), how and when to make PR, etc

**Comment by Asmit2952** [comment]
Instead of adding it to the Readme, how about making a separate file CONTRIBUTING.md?

**Comment by Asmit2952** [comment]
Ohh, I already started working on this issue @madhhuurrii . But you can still make a PR making a new file or by suggesting changes in mine :) 

I'll be happy to help you!!
