### ISSUE TITLE
Missing /objects in uri in example

### ISSUE THREAD

**Issue by lucas-cauhe** [semi-technologies/weaviate-io#114]
While going through [this](https://weaviate.io/developers/weaviate/v1.11.0/tutorials/how-to-perform-a-semantic-search.html#explore-graphql-function) tutorial, in the final part of the "explore graphql" section I believe there's a missing part of the uri in here:
`$ curl -s http://localhost:8080/v1/{id}
`
This didn't work for me (told me the path was not found) so I tweaked it, adding the '/objects' in the middle like this:
`$ curl -s http://localhost:8080/v1/objects/{id}`
what did work for me. Perhaps this happens due to a misconfiguration during my installation or it's just a silly docs issue🙃.

**Comment by etiennedi** [comment]
Great catch, thank you. Would you be willing to submit a small PR for this change?

**Comment by lucas-cauhe** [comment]
Done!

**Comment by bobvanluijt** [comment]
Merci @lucas-cauhe 💪
