### ISSUE TITLE
Issue with menu in non-current docs

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate-io#151]
### Code of Conduct

- [X] I have read and agree to the Weaviate's [Code of Conduct](https://github.com/semi-technologies/weaviate-io/blob/main/CODE_OF_CONDUCT.md)

### What part of document/web-page on weaviate.io is affected?

When I'm using the documentation and I'm using a non-current page (e.g., `developers/weaviate/v1.12.2`) I see the following menu:

<img width="182" alt="Screenshot 2022-07-06 at 15 01 20" src="https://user-images.githubusercontent.com/5509162/177556176-64a1021f-39fc-41a4-b3be-f8b04c4c0a28.png">

When using current (i.e., `developers/weaviate/current`) it works as desired.

<img width="188" alt="Screenshot 2022-07-06 at 15 01 12" src="https://user-images.githubusercontent.com/5509162/177556196-6bae470b-0ef9-4ed6-9dcd-849745250dbb.png">

**Comment by sebawita** [comment]
fixed with the latest code push :)
