### ISSUE TITLE
[Documentation Feedback]: Proposal for improving the Getting Started in 10 Minutes Doc

### ISSUE THREAD

**Issue by Winterflower** [semi-technologies/weaviate-io#162]
### Page URL

https://weaviate.io/developers/weaviate/current/getting-started/quick-start.html

### User feedback

Hi everyone!
I've been playing around with Weaviate on a cloud VM and would like to offer some feedback on the Getting Started in 10 minutes guide to, hopefully, get future users up to speed faster. 

### What currently works and what does not
The current guide relies a lot on dockerization to get the user up and running quickly, which I think is good, but at the risk of abstracting too much, so that the user, after having completed the Getting Started tutorial, doesn't really know enough about ingesting data or how to create a schema to then be able to immediately take what they learnt from the tutorial and start playing on their own. The links at the end of the tutorial do list further resources such as ingesting your own data and creating your own schema, but many of them are quite involved (which is fair enough, given it's a complicated piece of software) and not in the spirit of "get me up and running with my own cool stuff as fast as possible" 🏃‍♀️ 

I think what you would ideally want to cover in a Getting Started guide are the basics of 1) installation 2) ingesting your own data 3) querying it/doing something cool with it in such a way that after the tutorial is done, the user can take this basic scaffold and plug their own data into it/start building on their own. 

### Proposal
Create a Getting Started guide that takes a simple external dataset, such as the [IMDB reviews dataset from Hugging Face](https://huggingface.co/datasets/imdb), creates a simple schema for it and then ingests it using the Python client. This way, we could distill and integrate some of the knowledge in this Hackernoon article https://hackernoon.com/what-is-weaviate-and-how-to-create-data-schemas-in-it-7hy3460 into the tutorial instead of having to redirect the users there. 
I'm happy to take a first stab at this in a PR.

**Comment by bobvanluijt** [comment]
Thanks for sharing, @Winterflower - coincidentally, we've started [collecting documentation feedback](https://forms.gle/MDggDU9maKBxeTqM7) this week, and we are incorporating it in the docs and (especially) the getting started section. 

I'll close the issue for now, but please know that we've added the feedback to the list.
