### ISSUE TITLE
total number of objects in  class

### ISSUE THREAD

**Issue by SuperLiChen** [semi-technologies/weaviate-io#206]
### Code of Conduct

- [X] I have read and agree to the Weaviate's [Code of Conduct](https://github.com/semi-technologies/weaviate-io/blob/main/CODE_OF_CONDUCT.md)

### What part of document/web-page on weaviate.io is affected?

I hope to get the total number of objects in a class, but not find the api on guide,
Only find a restful  "GET /v1/objects?class={className}&limit={limit}" will return totalCount of limit.

**Comment by etiennedi** [comment]
Hi, you can use `{ Aggregate { ClassName { meta { count } } } }`, see [Aggregate](https://weaviate.io/developers/weaviate/current/graphql-references/aggregate.html). Does that answer your question? 

If it does, we would love to find out why you couldn't find that information in the docs, so we can improve it. cc @sebawita

**Comment by SuperLiChen** [comment]
Yes, this is feasible, thanks.

I think the total number of objects API should be in  [ /v1/objects](https://weaviate.io/developers/weaviate/current/restful-api-references/objects.html), so I didn't carefully check [gpaphql Aggregate](https://weaviate.io/developers/weaviate/current/graphql-references/aggregate.html)

**Comment by etiennedi** [comment]
Thanks for the feedback, this is really helpful.
