### ISSUE TITLE
Improve Documentation on Filters page

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate-io#34]
This page: https://weaviate.io/developers/weaviate/current/graphql-references/filters.html

Can be improved:

- There should be an explanation about different behavior of `string` and `text` fields on this page.
- There should be an explanation of word-boundary token splitting and the effects it has. Also with a link to semi-technologies/weaviate#1821 which will give the user full control over this process
- The page names everything filters, even things that aren't filters. This included `nearObject`, `nearVector`, etc. But also `limit` etc. Those need to be called parameters or operators to reduce the confusion, since they do not filter anything. Especially in the case of a `near<>` operator, the result set is exactly the same as unfiltered, just in a different order.

**Comment by bobvanluijt** [comment]
@laura-ham – can you help with this, please?

**Comment by etiennedi** [comment]
In addition to the above, I think we should also change the title of the page to something like "Filters & Search Parameters". I just wanted to send someone a link to the explanation about `nearVector`, but didn't find it in the docs. Then it occurred to me that it's probably under "Filters". Or we could even split this into multiple pages: (Where) Filters, Search Parameters.

**Comment by etiennedi** [comment]
I'm fixing the incorrect naming as part of the `v1.13.0` docs.

**Comment by etiennedi** [comment]
Bullet 2 from above is obsolete since we added tokenization support. Both options are now explained in detail.
