### ISSUE TITLE
Website takes really long to generate

### ISSUE THREAD

**Issue by laura-ham** [semi-technologies/weaviate-io#59]
Using `bundle exec jekyll serve` to show the website during developing takes really long (around 250 seconds). Is there a way to optimize this? 

(I'm using `bundle exec jekyll serve --incremental` to quickly refresh page content, but of course this doesn't regenerate the site structure)

**Comment by bobvanluijt** [comment]
We could remove older documentation (e.g., pre-v1) this would help a lot

**Comment by bobvanluijt** [comment]
I noticed that it clearly sits in the new modules for redirection. You might want to check out if you didn't create a loop or so
