### ISSUE TITLE
[Minor] Javascript in "how to query" example correct?

### ISSUE THREAD

**Issue by Ontopic** [semi-technologies/weaviate-io#88]
Thanks for doing such an extensive job on documentation in different languages! Still having some trouble setting everything up, but that's more because of my weird setup.

In the examples for "How to query" I couldn't help but feel that the javascript example is either "wrong" or requires some explanation, as to why i the javascript implementation the query string seems to be made be "embedded" through string concatination inside another part? Which doesn't seem to be the case in any of the query examples in the other languages.

I'm talking about the following line in https://weaviate.io/developers/weaviate/current/tutorials/how-to-query-data.html

```
path: ['inPublication", "Publication", "name'],
```

Is the usage of ' and " on purpose?

**Comment by Ontopic** [comment]
Now that I've looked at the .md file (https://github.com/semi-technologies/weaviate-io/blob/main/developers/weaviate/v1.11.0/tutorials/how-to-query-data.md) I can see why this might have gone wrong 😅

Would probably nice to fix this at some point in the docs. For now assuming a regular array of strings is required for `path`.

**Comment by bobvanluijt** [comment]
Ooo - well spotted @Ontopic 🙏  – feel free to change it in the docs :)

Will close it now
