### ISSUE TITLE
The architecture link in the contributor guide not working

### ISSUE THREAD

**Issue by soma2000-lang** [semi-technologies/weaviate-io#95]
The architecture[ link](https://github.com/semi-technologies/weaviate-io/compare/main...soma2000-lang:patch-1#diff-346bb80d348092e078ac043d7580f4485a753310bd027fe43be2c2636e7f0e53) is not working

**Comment by Iheanacho-ai** [comment]
please can i take this on

**Comment by laura-ham** [comment]
Similar to https://github.com/semi-technologies/weaviate-io/issues/92, this link is actually working so I'll close this issue.
